name: arre
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  provider: ^6.1.5
  sqflite: ^2.3.2
  audio_waveforms: ^1.3.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  just_audio: ^0.9.46

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: MonaSans
      fonts:
        - asset: assets/fonts/MonaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/MonaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/MonaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/MonaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MonaSans-Light.ttf
          weight: 300
  assets:
    - assets/home/
    - assets/splashscreen/
    - assets/audio_recorder/